# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-08-07 07:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0002_auto_20190806_1652'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserLeavingMesage',
            new_name='UserLeavingMessage',
        ),
    ]
