# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-08-06 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_auto_20190806_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.CharField(choices=[('success', '成功'), ('cancel', '取消'), ('wait', '待支付')], max_length=10, verbose_name='订单状态'),
        ),
    ]
